BoxStyles:
  BoldLines:
    CornerTopLeft: "┏"
    CornerTopRight: "┓"
    Side: "┃"
    Line: "━"
    CornerBottomLeft: "┗"
    CornerBottomRight: "┛"
  DoubleLines:
    CornerTopLeft: "╔"
    CornerTopRight: "╗"
    Side: "║"
    Line: "═"
    CornerBottomLeft: "╚"
    CornerBottomRight: "╝"
  BasicLines:
    CornerTopLeft: "+"
    CornerTopRight: "+"
    Side: "|"
    Line: "-"
    CornerBottomLeft: "+"
    CornerBottomRight: "+"
  ThinLines:
    CornerTopLeft: "┌"
    CornerTopRight: "┐"
    Side: "│"
    Line: "─"
    CornerBottomLeft: "└"
    CornerBottomRight: "┘"
  CurvyLines:
    CornerTopLeft: "╭"
    CornerTopRight: "╮"
    Side: "│"
    Line: "─"
    CornerBottomLeft: "╰"
    CornerBottomRight: "╯"
  PixelLines:
    CornerTopLeft: "▞"
    CornerTopRight: "▚"
    Side: "▝"
    Line: "▖"
    CornerBottomLeft: "└"
    CornerBottomRight: "┘"