BoxStyles:
  BoldLines:
    CornerTopLeft: "┏"
    CornerTopRight: "┓"
    Side: "┃"
    DividerLeft: "┠"
    DividerRight: "┨"
    Line: "━"
    CornerBottomLeft: "┗"
    CornerBottomRight: "┛"
  DoubleLines:
    CornerTopLeft: "╔"
    CornerTopRight: "╗"
    Side: "║"
    DividerLeft: "╠"
    DividerRight: "╣"
    Line: "═"
    CornerBottomLeft: "╚"
    CornerBottomRight: "╝"
  BasicLines:
    CornerTopLeft: "+"
    CornerTopRight: "+"
    Side: "|"
    DividerLeft: "|"
    DividerRight: "|"
    Line: "-"
    CornerBottomLeft: "+"
    CornerBottomRight: "+"
  ThinLines:
    CornerTopLeft: "┌"
    CornerTopRight: "┐"
    Side: "│"
    DividerLeft: "├"
    DividerRight: "┤"
    Line: "─"
    CornerBottomLeft: "└"
    CornerBottomRight: "┘"
  CurvyLines:
    CornerTopLeft: "╭"
    CornerTopRight: "╮"
    Side: "│"
    DividerLeft: "├"
    DividerRight: "┤"
    Line: "─"
    CornerBottomLeft: "╰"
    CornerBottomRight: "╯"